// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNiHt9BoCTzRcZQzdmnpxRq7uU9MoRSo4',
    appId: '1:971318709956:android:4392fec87334f56f568391',
    messagingSenderId: '971318709956',
    projectId: 'kitahack-app',
    storageBucket: 'kitahack-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS0xvTiT1ittvvYzIoW7D597YFKXoxvS4',
    appId: '1:971318709956:web:f80ee32eddf8496f568391',
    messagingSenderId: '971318709956',
    projectId: 'kitahack-app',
    authDomain: 'kitahack-app.firebaseapp.com',
    storageBucket: 'kitahack-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS0xvTiT1ittvvYzIoW7D597YFKXoxvS4',
    appId: '1:971318709956:web:d761c3e64f4cc0fc568391',
    messagingSenderId: '971318709956',
    projectId: 'kitahack-app',
    authDomain: 'kitahack-app.firebaseapp.com',
    storageBucket: 'kitahack-app.firebasestorage.app',
  );

}