// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKvMMwgMeU5dfO9h3l9kt6vFAVwkeojgg',
    appId: '1:64008081491:android:78d36d1ce1af3e503276a6',
    messagingSenderId: '64008081491',
    projectId: 'gen-lang-client-0596703750',
    storageBucket: 'gen-lang-client-0596703750.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfHv5QHkjV8GS5yIto-7DUqnhZRNd8cKA',
    appId: '1:64008081491:web:57581902aece732c3276a6',
    messagingSenderId: '64008081491',
    projectId: 'gen-lang-client-0596703750',
    authDomain: 'gen-lang-client-0596703750.firebaseapp.com',
    storageBucket: 'gen-lang-client-0596703750.firebasestorage.app',
    measurementId: 'G-LLKZSTD2JB',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfHv5QHkjV8GS5yIto-7DUqnhZRNd8cKA',
    appId: '1:64008081491:web:aef970ff12bdbbd23276a6',
    messagingSenderId: '64008081491',
    projectId: 'gen-lang-client-0596703750',
    authDomain: 'gen-lang-client-0596703750.firebaseapp.com',
    storageBucket: 'gen-lang-client-0596703750.firebasestorage.app',
    measurementId: 'G-ZS0D1CJ6KF',
  );

}