// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxhV3v_witI45_vc5JR0M8QJOjzjxy0_I',
    appId: '1:896519692444:android:dfc0060bccef07b7a4cd59',
    messagingSenderId: '896519692444',
    projectId: 'kitahack-app-e2fb3',
    storageBucket: 'kitahack-app-e2fb3.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4oVYZ9QS6Jw1lHsHXnVXBZkTgHHGtrFo',
    appId: '1:896519692444:web:18ee64da5514af12a4cd59',
    messagingSenderId: '896519692444',
    projectId: 'kitahack-app-e2fb3',
    authDomain: 'kitahack-app-e2fb3.firebaseapp.com',
    storageBucket: 'kitahack-app-e2fb3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4oVYZ9QS6Jw1lHsHXnVXBZkTgHHGtrFo',
    appId: '1:896519692444:web:91bab0a07d187193a4cd59',
    messagingSenderId: '896519692444',
    projectId: 'kitahack-app-e2fb3',
    authDomain: 'kitahack-app-e2fb3.firebaseapp.com',
    storageBucket: 'kitahack-app-e2fb3.firebasestorage.app',
  );

}